stages:
  - schedule
  - generate
  - pipeline

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules -e .yarn-cache

generate:
  stage: generate
  image: python:3.7-slim
  script: python generate-gitlab-ci.py
  artifacts:
    paths:
      - .gitlab-ci.generated.yml
  except:
    - schedule

pipeline:
  stage: pipeline
  trigger:
    include:
      - artifact: .gitlab-ci.generated.yml
        job: generate
    strategy: depend
  except:
    - schedule

# statica deployments

generate-statica:
  stage: generate
  image: python:3.7-slim
  script: python generate-gitlab-ci-statica.py
  artifacts:
    paths:
      - .gitlab-ci-statica.generated.yml
  except:
    - schedule

pipeline-statica:
  stage: pipeline
  trigger:
    include:
      - artifact: .gitlab-ci-statica.generated.yml
        job: generate-statica
    strategy: depend
  except:
    - schedule

# schedule jobs

auto_update_sessions_yml_from_training_crm:
  stage: schedule
  image: sikalabs/ci
  variables:
    GIT_AUTHOR_NAME: SikaLabs CI Bot
    GIT_COMMITTER_NAME: SikaLabs CI Bot
    GIT_COMMITTER_EMAIL: ci-bot@sikalabs.io
    GIT_AUTHOR_EMAIL: ci-bot@sikalabs.io
  script:
    - make auto-update-sessions-yml-from-training-crm
    - git remote set-url origin https://ci-bot:$GITLAB_TOKEN_CI_BOT@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git push origin HEAD:$CI_COMMIT_BRANCH
  only:
    - schedule
