stages:
  - push-to-github
  - schedule1
  - schedule2
  - generate
  - pipeline

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules -e .yarn-cache

push-to-github:
  image: sikalabs/ci
  stage: push-to-github
  script:
  - mkdir -p ~/.ssh
  - cp $GITHUB_PUSH_SSH_KEY_PRIV ~/.ssh/id_rsa
  - chmod 700 -R ~/.ssh
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - git remote add github-$CI_PIPELINE_ID git@github.com:ondrejsika/www.git
  - git push github-$CI_PIPELINE_ID $CI_COMMIT_SHA:$CI_COMMIT_BRANCH -f


generate:
  stage: generate
  image: python:3.7-slim
  script: python generate-gitlab-ci.py
  artifacts:
    paths:
      - .gitlab-ci.generated.yml
  except:
    - schedule
  needs: []

pipeline:
  stage: pipeline
  trigger:
    include:
      - artifact: .gitlab-ci.generated.yml
        job: generate
    strategy: depend
  except:
    - schedule
  needs:
    - generate

# statica deployments

generate-statica:
  stage: generate
  image: python:3.7-slim
  script: python generate-gitlab-ci-statica.py
  artifacts:
    paths:
      - .gitlab-ci-statica.generated.yml
  except:
    - schedule
  needs: []

pipeline-statica:
  stage: pipeline
  trigger:
    include:
      - artifact: .gitlab-ci-statica.generated.yml
        job: generate-statica
    strategy: depend
  except:
    - schedule
  needs:
    - generate-statica

# schedule jobs

auto_update_sessions_yml_from_training_crm:
  stage: schedule1
  image: sikalabs/ci
  variables:
    GIT_AUTHOR_NAME: SikaLabs CI Bot
    GIT_COMMITTER_NAME: SikaLabs CI Bot
    GIT_COMMITTER_EMAIL: ci-bot@sikalabs.io
    GIT_AUTHOR_EMAIL: ci-bot@sikalabs.io
  script:
    - make auto-update-sessions-yml-from-training-crm
    - git remote set-url origin https://ci-bot:$GITLAB_TOKEN_CI_BOT@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git push origin HEAD:$CI_COMMIT_BRANCH
  only:
    - schedule

auto_ncu_update:
  stage: schedule2
  image: sikalabs/ci-node
  variables:
    GIT_AUTHOR_NAME: SikaLabs CI Bot
    GIT_COMMITTER_NAME: SikaLabs CI Bot
    GIT_COMMITTER_EMAIL: ci-bot@sikalabs.io
    GIT_AUTHOR_EMAIL: ci-bot@sikalabs.io
  script:
    - yarn
    - make auto-ncu-update
    - cd sites20 && make auto-ncu-update
    - git remote set-url origin https://ci-bot:$GITLAB_TOKEN_CI_BOT@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git push origin HEAD:$CI_COMMIT_BRANCH
  only:
    - schedule
