stages:
  - generate
  - pipeline

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules

generate:
  stage: generate
  image: python:3.7-slim
  script: python generate-gitlab-ci.py
  artifacts:
    paths:
      - .gitlab-ci.generated.yml

pipeline:
  stage: pipeline
  trigger:
    include:
      - artifact: .gitlab-ci.generated.yml
        job: generate
    strategy: depend

# statica deployments

generate-statica:
  stage: generate
  image: python:3.7-slim
  script: python generate-gitlab-ci-statica.py
  artifacts:
    paths:
      - .gitlab-ci-statica.generated.yml

pipeline-statica:
  stage: pipeline
  trigger:
    include:
      - artifact: .gitlab-ci-statica.generated.yml
        job: generate-statica
    strategy: depend
